env:
  global:
    secure:
      - "YrDDQkvGMzT1I0I31Shmx0dL+7scjodXO7Y/EekpR7leQ0ylcU+NpXyGI9bAy0NUz6NkBm7IKyEclT6xAAYNmBqZyzuRkFGvjKb+FCwI7yXcvsr6mCzL6v/o2bR6orlxnPGAaNASwTqMHeMyHROQ8cAOCbb6kQH2pnMbepregh4"
      - "V8M23FOC90lPkVqZM0Ot6gDwqJFeWpoNcUsthmrB/25P7cVGEhZPogSGTjjuwUsXeLdCMthVOM0QBq/eQEH+V7EQhX44RF8ReyHpNKluVYzNKOU224EmrQrxKqX+hLPH4lOU3ryfuYlNpKbrANIVDDo3MGxyzZ4mOU1an1h0LyE"
    - "RAILS_ENV=test"
    - "API_KEY=$AIRBRAKE_API_KEY"
    - "TO=$RAILS_ENV"
    - "REVISION=$(git rev-parse HEAD)"
    - "REPO=psychedeli.ca"

language: ruby
rvm: 1.9.3
bundler_args: "--without=development:production"
script: "bundle exec rspec"

# Deploy to heroku when a build succeeds
after_success:
  # Install the Heroku gem (or the Heroku toolbelt)
  - "gem install heroku"
  # Add your Heroku git repo:
  - "git remote add heroku git@heroku.com:psychedelica.git"
  # Turn off warnings about SSH keys:
  - "echo 'Host heroku.com' >> ~/.ssh/config"
  - "echo '   StrictHostKeyChecking no' >> ~/.ssh/config"
  - "echo '   CheckHostIP no' >> ~/.ssh/config"
  - "echo '   UserKnownHostsFile=/dev/null' >> ~/.ssh/config"
  # Clear your current Heroku SSH keys:
  - "heroku keys:clear"
  # Add a new SSH key to Heroku
  - "yes | heroku keys:add"
  # Push to Heroku!
  - "yes | git push heroku master"
  # Notify Airbrake of deploy
  - "yes | bundle exec rake airbrake:deploy"
