env:
  global:
    secure: "IIJAZjKn1snxZlz8Ngio2iirUwctv+WN0nqIJxQpM65a0/UUvLTHZGCX6mSg\n2J+xyX8XFecd0ukOmjdKXz8UAnKq2nTD72KMIdCRqAgIxEZv3SmcD9eG05jJ\nOK6Lb7uwVbwuW0Ld/sZbmZ8B3f+qXmRSvFmo3pktsiPSkfTyWwE="
    secure: ""
    - "RAILS_ENV=test"
    - "API_KEY=$AIRBRAKE_API_KEY"
    - "TO=$RAILS_ENV"
    - "REVISION=$(git rev-parse HEAD)"
    - "REPO=psychedeli.ca"

language: ruby
rvm: 1.9.3
bundler_args: "--without=development"
script: "bundle exec rspec"

# Deploy to heroku when a build succeeds
after_success:
  # Install the Heroku gem (or the Heroku toolbelt)
  - "gem install heroku"
  # Add your Heroku git repo:
  - "git remote add heroku git@heroku.com:psychedelica.git"
  # Turn off warnings about SSH keys:
  - "echo 'Host heroku.com' >> ~/.ssh/config"
  - "echo '   StrictHostKeyChecking no' >> ~/.ssh/config"
  - "echo '   CheckHostIP no' >> ~/.ssh/config"
  - "echo '   UserKnownHostsFile=/dev/null' >> ~/.ssh/config"
  # Clear your current Heroku SSH keys:
  - "heroku keys:clear"
  # Add a new SSH key to Heroku
  - "yes | heroku keys:add"
  # Push to Heroku!
  - "yes | git push heroku master"
  # Notify Airbrake of deploy
  - "bundle exec rake airbrake:deploy"
