env:
  global:
  - secure: aAH8czTvOa7nC9A2rtgaqZazWZPcC+1rArAGKbvbjwe7C++qBgB4RC2hOt00t6oxSITVgEHXfVp4mzs2Q6A+4H0pog7zhrenH8U0k0xJWk2ueLHgKXurRYcIqffyLqB51wRdEq3GCdjC/gT0qW5rMesRvreLZPcQCRZaFKVcSSI=
  - secure: IcgR1qXENGdWzbfK5rjLOkfzDqvOW6bLsR7GXGcW0wwRkEBq1EmuLtm80VjAY/xjV0nVp6FV26+2nAvCbn0odAvi3smW2JWUTkWKpIN3oZS6Za5lmMgoLHuLB1XeBLhonoYv4G3iRHqOw/+fz/VXlcxYR4rK2iqR20AdiMbTZMI=
branches:
  only:
    - master
language: ruby
rvm: 2.0.0-p247
bundler_args: --without=development:production
script: bundle exec rspec --format=documentation
after_success: bundle exec rake deploy
