env:
  global:
    secure: "lPXozEpZZBFF1VcnKtzAm2l9qeHmDtOuF2SxKBWyltkAI8Fs8X0OOzqgD276\nI58PQKct2ysgOHfV/NHhf53J0T0i3lOFw8y4t0YtK5NS0Y70ZWL1dBcM9PFY\naVgqHOUTFXvMOUx5KuUGBWmr/6wNkxh1rhe8130v21n5woyxvTk="
language: ruby
rvm: 1.9.3
bundler_args: "--without=development"
script: "bundle exec rspec"

# Deploy to heroku when a build succeeds
after_success:
  # Install the Heroku gem (or the Heroku toolbelt)
  - "gem install heroku"
  # Add your Heroku git repo:
  - "git remote add heroku git@heroku.com:psychedelica.git"
  # Turn off warnings about SSH keys:
  - "echo 'Host heroku.com' >> ~/.ssh/config"
  - "echo '   StrictHostKeyChecking no' >> ~/.ssh/config"
  - "echo '   CheckHostIP no' >> ~/.ssh/config"
  - "echo '   UserKnownHostsFile=/dev/null' >> ~/.ssh/config"
  # Clear your current Heroku SSH keys:
  - "heroku keys:clear"
  # Add a new SSH key to Heroku
  - "yes | heroku keys:add"
  # Push to Heroku!
  - "yes | git push heroku master"
