# psychedeli.ca blog configuration

auto: false
destination: ./pub
markdown: redcarpet
pygments: true
permalink: pretty       # /category/YYYY/MM/DD/title
exclude: 
    - _drafts
    - Gemfile
    - Gemfile.lock
    - config.rb
    - config.ru
    - gen
    - tmp
    - src
    - css
    - js
    - swf
    - img
    