# psychedeli.ca blog configuration

auto: false
layouts: html
posts: doc
destination: pub
markdown: redcarpet
pygments: true
permalink: pretty       # /category/YYYY/MM/DD/title
exclude:
    - Gemfile
    - Gemfile.lock
    - config.rb
    - conaru
    - gen
    - tmp
    - src
    - swf
    - cfg
    - html
    - bin
