# psychedeli.ca blog configuration

auto: false
destination: ./public
markdown: redcarpet
pygments: true
permalink: pretty       # /category/YYYY/MM/DD/title
exclude: ['_drafts', 'Gemfile', 'Gemfile.lock', 'config.rb', 'recompile', 'src']