auto: false
source: ./app/jekyll
layouts: layouts # relative from the source dir
posts: articles
destination: ./public
plugins: ./lib/jekyll
markdown: redcarpet
pygments: true
permalink: pretty       # /category/YYYY/MM/DD/title
exclude:
- layouts
