auto: false
source: ./app
layouts: views/layouts # relative from the source dir
posts: documents/articles
destination: ./public
plugins: ./lib/jekyll
markdown: redcarpet
pygments: true
permalink: pretty       # /category/YYYY/MM/DD/title
exclude:
- html
- doc
- css
- js
- img
